[workspace]
members = [
    "crates/vision-calibration",
    "crates/vision-calibration-core",
    "crates/vision-calibration-linear",
    "crates/vision-calibration-optim",
    "crates/vision-calibration-pipeline",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Vitaly Vorobyev <vit.vorobiev@gmail.com>"]
homepage = "https://vitalyvorobyev.github.io/calibration"
repository = "https://github.com/VitalyVorobyev/calibration-rs"

[workspace.dependencies]
nalgebra = { version = "0.34", features = ["serde-serialize"] }
num-dual = "0.13.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
