[book]
authors = ["Vitaly Vorobyev"]
language = "en"
src = "src"
title = "calibration-rs Book"

[preprocessor.katex]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/VitalyVorobyev/calibration-rs"
mathjax-support = false

