[book]
authors = ["Vitaly Vorobyev"]
language = "en"
multilingual = false
src = "src"
title = "calibration-rs Book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/VitalyVorobyev/calibration-rs"

