[package]
name = "calib-core"
version = "0.1.0"
edition = "2021"

[features]
tracing = ["dep:tracing"]

[dependencies]
nalgebra = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { version = "0.9" }
tracing = { version = "0.1", optional=true }
